version: '3.8'

services:
  roberto:
    image: ghcr.io/thetipo01/restroberto:latest
    container_name: roberto
    ports:
      - "8087:8087"
    volumes:
      # CAMBIATO: Il percorso interno ora è quello reale di Wine
      - ./config.yml:/root/.wine/drive_c/roberto/config.yml
      # Se vuoi anche i log o i file temporanei:
      - ./temp:/root/.wine/drive_c/roberto/temp
    restart: unless-stopped
    # Decommenta securityopt per allentare restrizioni e farlo funzionare in cloud hosting
    #security_opt:
    #  - seccomp:unconfined
